USE [master]
GO
/****** Object:  Database [OrdenesPPI]    Script Date: 27/11/2024 11:02:48 ******/
CREATE DATABASE [OrdenesPPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OrdenesPPI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\OrdenesPPI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OrdenesPPI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\OrdenesPPI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [OrdenesPPI] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OrdenesPPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [OrdenesPPI] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OrdenesPPI] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OrdenesPPI] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OrdenesPPI] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OrdenesPPI] SET ARITHABORT OFF 
GO
ALTER DATABASE [OrdenesPPI] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OrdenesPPI] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OrdenesPPI] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OrdenesPPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OrdenesPPI] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OrdenesPPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OrdenesPPI] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OrdenesPPI] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OrdenesPPI] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OrdenesPPI] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OrdenesPPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OrdenesPPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OrdenesPPI] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [OrdenesPPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [OrdenesPPI] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OrdenesPPI] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OrdenesPPI] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [OrdenesPPI] SET RECOVERY FULL 
GO
ALTER DATABASE [OrdenesPPI] SET  MULTI_USER 
GO
ALTER DATABASE [OrdenesPPI] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OrdenesPPI] SET DB_CHAINING OFF 
GO
ALTER DATABASE [OrdenesPPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [OrdenesPPI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OrdenesPPI] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [OrdenesPPI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'OrdenesPPI', N'ON'
GO
ALTER DATABASE [OrdenesPPI] SET QUERY_STORE = ON
GO
ALTER DATABASE [OrdenesPPI] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [OrdenesPPI]
GO
/****** Object:  Table [dbo].[Activos]    Script Date: 27/11/2024 11:02:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Activos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ticker] [nvarchar](32) NOT NULL,
	[Nombre] [nvarchar](100) NOT NULL,
	[PrecioUnitario] [decimal](10, 4) NOT NULL,
	[TipoActivoId] [int] NOT NULL,
 CONSTRAINT [PK_Activos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Cuentas]    Script Date: 27/11/2024 11:02:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Cuentas](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Cuentas] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estados]    Script Date: 27/11/2024 11:02:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estados](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[descripcionEstado] [nvarchar](20) NOT NULL,
 CONSTRAINT [PK_Estados] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Ordenes]    Script Date: 27/11/2024 11:02:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ordenes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CuentaId] [int] NOT NULL,
	[ActivoId] [int] NOT NULL,
	[EstadoId] [int] NOT NULL,
	[Operacion] [varchar](5) NOT NULL,
	[Cantidad] [decimal](10, 4) NOT NULL,
	[MontoTotal] [decimal](10, 4) NOT NULL,
	[Comisiones] [decimal](10, 4) NOT NULL,
	[Impuestos] [decimal](10, 4) NOT NULL,
	[Monto] [decimal](10, 4) NOT NULL,
 CONSTRAINT [PK_Ordenes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[V_Ordenes]    Script Date: 27/11/2024 11:02:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[V_Ordenes] AS SELECT O.Id As IdOrden,C.Id  As IdCuenta, C.Descripcion As NombreCuenta, A.Nombre As NombreActivo, O.Cantidad,A.PrecioUnitario As Precio,E.descripcionEstado As Estado,O.MontoTotal, O.Operacion FROM Ordenes O INNER JOIN Cuentas C ON C.Id = O.CuentaId INNER JOIN Activos A ON A.Id = O.ActivoId INNER JOIN Estados E ON E.Id = O.EstadoId; 
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 27/11/2024 11:02:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tipoactivos]    Script Date: 27/11/2024 11:02:48 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tipoactivos](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_Tipoactivos] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_Activos_TipoActivoId]    Script Date: 27/11/2024 11:02:48 ******/
CREATE NONCLUSTERED INDEX [IX_Activos_TipoActivoId] ON [dbo].[Activos]
(
	[TipoActivoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Ordenes_ActivoId]    Script Date: 27/11/2024 11:02:48 ******/
CREATE NONCLUSTERED INDEX [IX_Ordenes_ActivoId] ON [dbo].[Ordenes]
(
	[ActivoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Ordenes_CuentaId]    Script Date: 27/11/2024 11:02:48 ******/
CREATE NONCLUSTERED INDEX [IX_Ordenes_CuentaId] ON [dbo].[Ordenes]
(
	[CuentaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Ordenes_EstadoId]    Script Date: 27/11/2024 11:02:48 ******/
CREATE NONCLUSTERED INDEX [IX_Ordenes_EstadoId] ON [dbo].[Ordenes]
(
	[EstadoId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Ordenes] ADD  DEFAULT ((0.0)) FOR [Comisiones]
GO
ALTER TABLE [dbo].[Ordenes] ADD  DEFAULT ((0.0)) FOR [Impuestos]
GO
ALTER TABLE [dbo].[Ordenes] ADD  DEFAULT ((0.0)) FOR [Monto]
GO
ALTER TABLE [dbo].[Activos]  WITH CHECK ADD  CONSTRAINT [FK_Activos_Tipoactivos_TipoActivoId] FOREIGN KEY([TipoActivoId])
REFERENCES [dbo].[Tipoactivos] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Activos] CHECK CONSTRAINT [FK_Activos_Tipoactivos_TipoActivoId]
GO
ALTER TABLE [dbo].[Ordenes]  WITH CHECK ADD  CONSTRAINT [FK_Ordenes_Activos_ActivoId] FOREIGN KEY([ActivoId])
REFERENCES [dbo].[Activos] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Ordenes] CHECK CONSTRAINT [FK_Ordenes_Activos_ActivoId]
GO
ALTER TABLE [dbo].[Ordenes]  WITH CHECK ADD  CONSTRAINT [FK_Ordenes_Cuentas_CuentaId] FOREIGN KEY([CuentaId])
REFERENCES [dbo].[Cuentas] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Ordenes] CHECK CONSTRAINT [FK_Ordenes_Cuentas_CuentaId]
GO
ALTER TABLE [dbo].[Ordenes]  WITH CHECK ADD  CONSTRAINT [FK_Ordenes_Estados_EstadoId] FOREIGN KEY([EstadoId])
REFERENCES [dbo].[Estados] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[Ordenes] CHECK CONSTRAINT [FK_Ordenes_Estados_EstadoId]
GO
USE [master]
GO
ALTER DATABASE [OrdenesPPI] SET  READ_WRITE 
GO

